version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - API_URL=http://127.0.0.1:5000
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./models:/app/models
